# Generated by Django 3.0.2 on 2020-01-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='summary',
            field=models.TextField(default='Default'),
        ),
    ]
