# Generated by Django 3.0.2 on 2020-01-20 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='is_deleted',
        ),
    ]
